clippy(oxide-auth-poem): resolve mismatched_lifetime_syntaxes
Starting in Rust 1.89.0, a warn-by-default lint called
mismatched_lifetime_syntaxes was added.

According to the Rust 1.89.0 release notes:

This lint detects when the same lifetime is referred to by different
syntax categories between function arguments and return values, which
can be confusing to read, especially in unsafe code.

More information about this link can be found in the Rust 1.89.0 release
notes and the introduction PR(rust-lang/rust#138677).

An example warning addressed by this change can be seen below:

error: hiding a lifetime that's elided elsewhere is confusing
  --> oxide-auth-poem/src/request.rs:60:19
   |
60 |     fn authheader(&mut self) -> Result<Option<Cow<str>>, Self::Error> {
   |                   ^^^^^^^^^                   ^^^^^^^^ the same lifetime is hidden here
   |                   |
   |                   the lifetime is elided here
   |
   = help: the same lifetime is referred to in inconsistent ways, making the signature confusing
help: use `'_` for type paths
   |
60 |     fn authheader(&mut self) -> Result<Option<Cow<'_, str>>, Self::Error> {
   |                                                   +++

Link: https://releases.rs/docs/1.89.0/#language
Link: https://github.com/rust-lang/rust/pull/138677
Signed-off-by: Abe Kohandel <abe@kodebooth.com>