clippy(oxide-auth): mark large_enum_variant as allow
The large_enum_variant lint discourages use of enum with large variation
in the variant sizes. The suggestion is to box the large variant which
would be a breaking change for this library, so let's deffer this until
a later time. Each instance of the warning is marked individually
instead of a blanket clippy allow configuration to prevent addition of
new instances of this warning.

Example warning being silenced:

error: large size difference between variants
   --> oxide-auth/src/code_grant/resource.rs:125:1
    |
125 | / pub enum Input<'req> {
126 | |     /// Provide the queried (bearer) token.
127 | |     Recovered(Option<Grant>),
    | |     ------------------------ the largest variant contains at least 248 bytes
128 | |     /// Determine the scopes of requested resource.
129 | |     Scopes(&'req [Scope]),
    | |     --------------------- the second-largest variant contains at least 16 bytes
...   |
136 | |     None,
137 | | }
    | |_^ the entire enum is at least 248 bytes
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/rust-1.92.0/index.html#large_enum_variant
    = note: `-D clippy::large-enum-variant` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(clippy::large_enum_variant)]`
help: consider boxing the large fields or introducing indirection in some other way to reduce the total size of the enum
    |
127 -     Recovered(Option<Grant>),
127 +     Recovered(Box<Option<Grant>>),
    |

Link: https://rust-lang.github.io/rust-clippy/rust-1.92.0/index.html#large_enum_variant
Signed-off-by: Abe Kohandel <abe@kodebooth.com>