clippy(oxide-auth-async): mark large_enum_variant as allow
The large_enum_variant lint discourages use of enum with large variation
in the variant sizes. The suggestion is to box the large variant which
would be a breaking change for this library, so let's deffer this until
a later time. Each instance of the warning is marked individually
instead of a blanket clippy allow configuration to prevent addition of
new instances of this warning.

Example warning being silenced:

error: large size difference between variants
   --> oxide-auth-async/src/endpoint/authorization.rs:72:1
    |
 72 | /   enum AuthorizationPartialInner<'a, E: 'a, R: 'a>
 73 | |   where
 74 | |       E: Endpoint<R> + Send,
 75 | |       R: WebRequest,
...   |
 78 | | /     Pending {
 79 | | |         /// A utility struct with which the request can be decided.
 80 | | |         pending: AuthorizationPending<'a, E, R>,
 81 | | |     },
    | | |_____- the largest variant contains at least 248 bytes
...   |
 84 | | /     Failed {
 85 | | |         /// The request passed in.
 86 | | |         request: R,
...   | |
 92 | | |         response: R::Response,
 93 | | |     },
    | | |_____- the second-largest variant contains at least 0 bytes
...   |
102 | |       },
103 | |   }
    | |___^ the entire enum is at least 248 bytes
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/rust-1.92.0/index.html#large_enum_variant
    = note: `-D clippy::large-enum-variant` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(clippy::large_enum_variant)]`
help: consider boxing the large fields or introducing indirection in some other way to reduce the total size of the enum
    |
 80 -         pending: AuthorizationPending<'a, E, R>,
 80 +         pending: Box<AuthorizationPending<'a, E, R>>,
    |

Link: https://rust-lang.github.io/rust-clippy/rust-1.92.0/index.html#large_enum_variant
Signed-off-by: Abe Kohandel <abe@kodebooth.com>