clippy(oxide-auth): mark result_large_err as allow
The result_large_err lint discourages use of large error types as they
can result in accumulation of large stack based objects. The suggestion
is to box the error type which would be a breaking change for this
library, so let's deffer this until a later time. Each instance of the
warning is marked individually instead of a blanket clippy allow
configuration to prevent addition of new instances of this warning.

Example warning being silenced:

error: the `Err`-variant returned from this function is very large
   --> oxide-auth/src/code_grant/authorization.rs:283:43
    |
283 |     fn validate(request: &dyn Request) -> Result<AuthorizationState> {
    |                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
...
504 |     Redirect(ErrorUrl),
    |     ------------------ the largest variant contains at least 144 bytes
    |
    = help: try reducing the size of `code_grant::authorization::Error`, for example by boxing large elements or replacing it with `Box<code_grant::authorization::Error>`
    = help: for further information visit https://rust-lang.github.io/rust-clippy/rust-1.92.0/index.html#result_large_err
    = note: `-D clippy::result-large-err` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(clippy::result_large_err)]`

Link: https://rust-lang.github.io/rust-clippy/beta/index.html#result_large_err
Signed-off-by: Abe Kohandel <abe@kodebooth.com>