clippy(oxide-auth): mark result_unit_err as allow
The result_unit_err lint discourages use of a () type for a public
function. Clippy is also smart enough to prevent a type alias such as
below:

pub type OAuthOpaqueError = ();

Resolving this lint would be a breaking change for this library, so
let's deffer this until a later time. Each instance of the warning is
marked individually instead of a blanket clippy allow configuration to
prevent addition of new instances of this warning.

Example warning being silenced:

error: this returns a `Result<_, ()>`
  --> oxide-auth/src/primitives/issuer.rs:25:5
   |
25 |     fn issue(&mut self, grant: Grant) -> Result<IssuedToken, ()>;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: use a custom `Error` type instead
   = help: for further information visit https://rust-lang.github.io/rust-clippy/beta/index.html#result_unit_err

Link: https://rust-lang.github.io/rust-clippy/beta/index.html#result_unit_err
Link: https://github.com/197g/oxide-auth/pull/183#issuecomment-1866548192
Signed-off-by: Abe Kohandel <abe@kodebooth.com>